### ISSUE TITLE
HW "expert signup sheet

### ISSUE THREAD

**Issue by timab25** [rldm/fall-2017#15]
setup “sign up” sheet for TAs to pick one(or more) HW assignments that they are to become the “expert” on.  They should be prepared to review common questions at the beginning of office hours.  Answer office hour questions. Answer piazza questions.  Stimulate Piazza discussions.

**Comment by mimoralea** [comment]
https://docs.google.com/spreadsheets/d/1vZFiq9weySiC9t0eNeiF_EcKbBTnUpOvlQPgja9fnHI/edit#gid=0
